version: '3.3'
services:
  postDB:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'postDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'

      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'

      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'

    volumes:
      - my-db:/var/lib/mysql
    networks:
      - "labb2network"
  app:
    depends_on:
      - postDB
    image: postbackend

    build: ./
    ports:
      - "8082:8080"
    expose:
      - "8082"
    command: "mvn spring-boot:run"
    networks:
      - "labb2network"
volumes:
  my-db:
networks:
  labb2network: