version: '3.3'
services:
  chatDB:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'chatDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'

      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'

      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'

    volumes:
      - my-db:/var/lib/mysql
    networks:
      - "labb2network"
  app:
    container_name: chatBackend
    depends_on:
      - chatDB
    image: chatbackend

    build: ./
    ports:
      - "8083:8080"
    expose:
      - "8083"
    command: "mvn spring-boot:run -X"
    networks:
      - "labb2network"

volumes:
  my-db:
networks:
  labb2network: