  version: '3.8'
  services:
    mongodb:
      image : mongo
      container_name: mongodb
      environment:
        - PUID=1000
        - PGID=1000
      ports:
        - "27017:27017"
      expose:
        - "27017"
      restart: unless-stopped
      networks:
        - "vertxnetwork"
    app:
      depends_on:
        - mongodb
      image: vertxbackend

      build: ./
      ports:
        - "8888:8888"
      expose:
        - "8888"
      command: "./mvnw clean compile exec:java"
      networks:
      - "vertxnetwork"
  networks:
    vertxnetwork:
