apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
        - name: userapi
          image: userbackend
          ports:
            - containerPort: 8081
              name: service-port
          imagePullPolicy: Never
